name: CI
on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
      
      - name: Setup themes
        run: |
          git submodule update --init --recursive
#          cd themes/hello-friend-ng
#          git checkout 4c3a69eaa6b3747fc5344fa4e1311459d6e0b88f
  
      - name: Build
        id: build
        run: hugo --minify

      - name: Deploy
        if: ${{ steps.build.outcome == 'success' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          external_repository: sidneiweber/sidneiweber.github.io
          publish_dir: ./public
          user_name: sidneiweber
          commit_message: ${{ github.event.head_commit.message }}
          user_email: sidneiweber@gmail.com
          publish_branch: main
